/**
 * AI-Powered Business Consultant - Frontend Application
 * Fully responsive client-side SPA compatible with Vercel & GitHub deployment.
 */

// Global App State
const AppState = {
    currentUser: null,
    apiKey: localStorage.getItem('gemini_api_key') || '',
    defaultKey: '',
    profile: null,
    chatMessages: [],
    selectedImageBase64: null,
    selectedImageMime: null
};

// System instruction for Gemini executive business consultant
const CONSULTANT_SYSTEM_PROMPT = 
`You are an executive Senior AI Business Consultant and Strategy Advisor.
Provide clear, actionable, structured, and insightful business recommendations.
Structure your answers with:
1. Executive Summary / Direct Answer
2. Strategic Recommendations (Numbered & Actionable)
3. Financial / Operational Considerations
4. Next Steps
Keep advice professional, realistic, and tailored to the client's business context.`;

// ==============================================================================
// STORAGE & AUTHENTICATION HELPERS
// ==============================================================================

function getStoredUsers() {
    try {
        return JSON.parse(localStorage.getItem('biz_users') || '[]');
    } catch (e) {
        return [];
    }
}

function saveStoredUsers(users) {
    localStorage.setItem('biz_users', JSON.stringify(users));
}

function getStoredProfile(userId) {
    try {
        return JSON.parse(localStorage.getItem(`biz_profile_${userId}`)) || {
            businessName: "My Growing Venture",
            industry: "Retail & Services",
            budget: "$10,000 / month",
            goals: "Acquire more high-value repeat customers and optimize margins",
            targetCustomers: "Working professionals and digital consumers"
        };
    } catch (e) {
        return null;
    }
}

function saveStoredProfile(userId, profile) {
    localStorage.setItem(`biz_profile_${userId}`, JSON.stringify(profile));
}

function getStoredChat(userId) {
    try {
        return JSON.parse(localStorage.getItem(`biz_chat_${userId}`) || '[]');
    } catch (e) {
        return [];
    }
}

function saveStoredChat(userId, messages) {
    localStorage.setItem(`biz_chat_${userId}`, JSON.stringify(messages));
}

// Simple fast SHA-256 for demo client-side hashing
async function hashPassword(str) {
    const encoder = new TextEncoder();
    const data = encoder.encode(str + "_ai_biz_salt");
    const hashBuffer = await crypto.subtle.digest('SHA-256', data);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
}

// ==============================================================================
// GEMINI 2.5 FLASH API CLIENT
// ==============================================================================

function getActiveApiKey() {
    return AppState.apiKey.trim() || AppState.defaultKey.trim();
}

async function callGeminiText(prompt, businessContext) {
    const key = getActiveApiKey();
    if (!key) {
        throw new Error("Gemini API key is not configured. Click 'Configure API Key' in the top right to paste your free Google Gemini API key.");
    }

    let fullPrompt = prompt;
    if (businessContext && businessContext.businessName) {
        fullPrompt = `[Client Business Context: Company: ${businessContext.businessName}, Industry: ${businessContext.industry}, Budget: ${businessContext.budget}, Goals: ${businessContext.goals}, Target Customers: ${businessContext.targetCustomers}]\n\nClient Question:\n${prompt}`;
    }

    const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${encodeURIComponent(key)}`;

    const requestBody = {
        contents: [
            {
                role: "user",
                parts: [{ text: fullPrompt }]
            }
        ],
        systemInstruction: {
            parts: [{ text: CONSULTANT_SYSTEM_PROMPT }]
        }
    };

    const res = await fetch(endpoint, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(requestBody)
    });

    if (!res.ok) {
        const errorData = await res.json().catch(() => ({}));
        const msg = errorData.error?.message || `HTTP ${res.status} error`;
        throw new Error(msg);
    }

    const data = await res.json();
    const replyText = data.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!replyText) {
        throw new Error("No response content generated by model.");
    }
    return replyText;
}

async function callGeminiVision(base64Data, mimeType, customPrompt, businessContext) {
    const key = getActiveApiKey();
    if (!key) {
        throw new Error("Gemini API key is not configured. Click 'Configure API Key' in the top right to paste your free Google Gemini API key.");
    }

    let promptText = "You are an executive AI Business Consultant. Please inspect and analyze this business asset (storefront, product, invoice, chart, or retail display).\n" +
        "1. Identify what is depicted.\n" +
        "2. Provide key business observations and strategic insights.\n" +
        "3. Recommend actionable growth, pricing, or operational improvements.\n";

    if (businessContext && businessContext.businessName) {
        promptText += `\nClient Business Context: ${businessContext.businessName} (${businessContext.industry}).`;
    }
    if (customPrompt && customPrompt.trim()) {
        promptText += `\nClient's specific inquiry: ${customPrompt.trim()}`;
    }

    const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${encodeURIComponent(key)}`;

    const requestBody = {
        contents: [
            {
                role: "user",
                parts: [
                    { text: promptText },
                    {
                        inlineData: {
                            mimeType: mimeType || "image/jpeg",
                            data: base64Data
                        }
                    }
                ]
            }
        ],
        systemInstruction: {
            parts: [{ text: CONSULTANT_SYSTEM_PROMPT }]
        }
    };

    const res = await fetch(endpoint, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(requestBody)
    });

    if (!res.ok) {
        const errorData = await res.json().catch(() => ({}));
        const msg = errorData.error?.message || `HTTP ${res.status} error`;
        throw new Error(msg);
    }

    const data = await res.json();
    const replyText = data.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!replyText) {
        throw new Error("No response content generated by model.");
    }
    return replyText;
}

// ==============================================================================
// ROUTING & NAVIGATION
// ==============================================================================

function getNormalizedRoute() {
    // Check hash first (e.g. #chat, #dashboard)
    const hash = window.location.hash.replace('#', '').trim();
    if (hash) {
        const cleanHash = hash.split('?')[0].replace(/^\//, '');
        if (cleanHash) return cleanHash;
    }

    // Check pathname (e.g. /chat, /dashboard)
    const path = window.location.pathname.replace(/^\//, '').split('?')[0];
    if (path && path !== 'index.html') {
        return path;
    }
    return 'dashboard';
}

function navigateTo(route) {
    // We update hash to ensure no 404 on refresh on any static host,
    // while keeping history state clean
    window.location.hash = `#${route}`;
    renderRoute(route);
}

// Global alert notification
function showAlert(message, type = 'info') {
    const container = document.getElementById('flashContainer');
    if (!container) return;
    const alertDiv = document.createElement('div');
    alertDiv.className = `alert alert-${type}`;
    alertDiv.innerHTML = `<span>${message}</span><button onclick="this.parentElement.remove()" style="background:none;border:none;cursor:pointer;font-weight:bold;">&times;</button>`;
    container.innerHTML = '';
    container.appendChild(alertDiv);
    setTimeout(() => {
        if (alertDiv.parentElement) alertDiv.remove();
    }, 6000);
}

// ==============================================================================
// RENDERERS FOR SCREENS
// ==============================================================================

function renderNavbar() {
    const navMenu = document.getElementById('navMenu');
    const brandLink = document.getElementById('brandLink');
    if (!navMenu) return;

    brandLink.onclick = () => navigateTo(AppState.currentUser ? 'dashboard' : 'login');

    const keyStatusText = getActiveApiKey() ? "🔑 API Key: Active" : "⚠️ Set Gemini API Key";
    const keyStatusClass = getActiveApiKey() ? "api-key-pill" : "api-key-pill alert-warning";

    if (AppState.currentUser) {
        navMenu.innerHTML = `
            <li><a href="#dashboard" class="${isRouteActive('dashboard') ? 'active' : ''}">Dashboard</a></li>
            <li><a href="#chat" class="${isRouteActive('chat') ? 'active' : ''}">Ask AI Consultant</a></li>
            <li><a href="#image-analysis" class="${isRouteActive('image-analysis') ? 'active' : ''}">Image Analysis</a></li>
            <li><a href="#profile" class="${isRouteActive('profile') ? 'active' : ''}">Business Profile</a></li>
            <li><button class="${keyStatusClass}" onclick="openApiKeyModal()">${keyStatusText}</button></li>
            <li><a href="javascript:void(0)" onclick="handleLogout()" class="nav-btn-logout">Logout</a></li>
        `;
    } else {
        navMenu.innerHTML = `
            <li><a href="#login" class="${isRouteActive('login') ? 'active' : ''}">Log In</a></li>
            <li><a href="#register" class="${isRouteActive('register') ? 'active' : ''}">Sign Up</a></li>
            <li><button class="${keyStatusClass}" onclick="openApiKeyModal()">${keyStatusText}</button></li>
        `;
    }
}

function isRouteActive(r) {
    return getNormalizedRoute() === r;
}

function renderRoute(route) {
    const mainContainer = document.getElementById('mainContent');
    if (!mainContainer) return;

    // Check Authentication: unauthenticated users redirect to login
    if (!AppState.currentUser && route !== 'login' && route !== 'register') {
        route = 'login';
        window.location.hash = '#login';
    } else if (AppState.currentUser && (route === 'login' || route === 'register')) {
        route = 'dashboard';
        window.location.hash = '#dashboard';
    }

    renderNavbar();

    switch (route) {
        case 'login':
            renderLoginView(mainContainer);
            break;
        case 'register':
            renderRegisterView(mainContainer);
            break;
        case 'dashboard':
            renderDashboardView(mainContainer);
            break;
        case 'chat':
            renderChatView(mainContainer);
            break;
        case 'image-analysis':
            renderImageView(mainContainer);
            break;
        case 'profile':
            renderProfileView(mainContainer);
            break;
        default:
            renderDashboardView(mainContainer);
            break;
    }
}

// ------------------------------------------------------------------------------
// 1. LOGIN & REGISTRATION
// ------------------------------------------------------------------------------

function renderLoginView(container) {
    container.innerHTML = `
        <div class="auth-wrapper">
            <div class="auth-card">
                <div class="auth-brand">
                    <div class="auth-brand-icon">💼</div>
                    <h1>Welcome Back</h1>
                    <p>Log in to access your AI Business Consultant dashboard</p>
                </div>
                <form id="loginForm">
                    <div class="form-group">
                        <label for="loginEmail" class="form-label">Email Address</label>
                        <input type="email" id="loginEmail" class="form-control" placeholder="you@company.com" required autocomplete="email">
                    </div>
                    <div class="form-group">
                        <label for="loginPassword" class="form-label">Password</label>
                        <input type="password" id="loginPassword" class="form-control" placeholder="Enter your password" required autocomplete="current-password">
                    </div>
                    <button type="submit" class="btn btn-primary btn-block" style="margin-top: 1.2rem;">
                        Log In to Dashboard
                    </button>
                </form>
                <div class="auth-footer">
                    Don't have an account? <a href="#register">Sign Up</a>
                </div>
            </div>
        </div>
    `;

    document.getElementById('loginForm').onsubmit = async (e) => {
        e.preventDefault();
        const email = document.getElementById('loginEmail').value.trim().toLowerCase();
        const pass = document.getElementById('loginPassword').value.trim();

        if (!email || !pass) {
            showAlert("Please enter both email and password.", "danger");
            return;
        }

        const users = getStoredUsers();
        const user = users.find(u => u.email.toLowerCase() === email);
        if (!user) {
            showAlert("No account found with this email. Please sign up.", "danger");
            return;
        }

        const hash = await hashPassword(pass);
        if (user.passwordHash !== hash) {
            showAlert("Invalid password. Please check your credentials.", "danger");
            return;
        }

        // Set session
        AppState.currentUser = user;
        localStorage.setItem('biz_current_user', JSON.stringify(user));
        AppState.profile = getStoredProfile(user.id);
        AppState.chatMessages = getStoredChat(user.id);

        showAlert(`Welcome back, ${user.name}!`, "success");
        navigateTo('dashboard');
    };
}

function renderRegisterView(container) {
    container.innerHTML = `
        <div class="auth-wrapper">
            <div class="auth-card">
                <div class="auth-brand">
                    <div class="auth-brand-icon">📈</div>
                    <h1>Create Account</h1>
                    <p>Receive tailored executive strategy for your business</p>
                </div>
                <form id="registerForm">
                    <div class="form-group">
                        <label for="regName" class="form-label">Full Name</label>
                        <input type="text" id="regName" class="form-control" placeholder="e.g. Sarah Jenkins" required autocomplete="name">
                    </div>
                    <div class="form-group">
                        <label for="regEmail" class="form-label">Email Address</label>
                        <input type="email" id="regEmail" class="form-control" placeholder="you@company.com" required autocomplete="email">
                    </div>
                    <div class="form-group">
                        <label for="regPassword" class="form-label">Password</label>
                        <input type="password" id="regPassword" class="form-control" placeholder="Minimum 6 characters" minlength="6" required autocomplete="new-password">
                    </div>
                    <button type="submit" class="btn btn-primary btn-block" style="margin-top: 1.2rem;">
                        Create Free Account
                    </button>
                </form>
                <div class="auth-footer">
                    Already have an account? <a href="#login">Log In</a>
                </div>
            </div>
        </div>
    `;

    document.getElementById('registerForm').onsubmit = async (e) => {
        e.preventDefault();
        const name = document.getElementById('regName').value.trim();
        const email = document.getElementById('regEmail').value.trim().toLowerCase();
        const pass = document.getElementById('regPassword').value.trim();

        if (!name || !email || !pass) {
            showAlert("Please fill in all registration fields.", "danger");
            return;
        }

        if (pass.length < 6) {
            showAlert("Password must be at least 6 characters.", "danger");
            return;
        }

        const users = getStoredUsers();
        if (users.some(u => u.email === email)) {
            showAlert("An account with this email already exists. Please log in.", "danger");
            return;
        }

        const hash = await hashPassword(pass);
        const newUser = {
            id: Date.now(),
            name: name,
            email: email,
            passwordHash: hash,
            createdAt: new Date().toISOString()
        };

        users.push(newUser);
        saveStoredUsers(users);

        // Initialize default profile
        const defaultProf = {
            businessName: `${name}'s Venture`,
            industry: "Retail & Services",
            budget: "$15,000 / month",
            goals: "Accelerate revenue growth & improve customer retention",
            targetCustomers: "Urban professionals & digital consumers"
        };
        saveStoredProfile(newUser.id, defaultProf);

        AppState.currentUser = newUser;
        localStorage.setItem('biz_current_user', JSON.stringify(newUser));
        AppState.profile = defaultProf;
        AppState.chatMessages = [];

        showAlert("Account created successfully! Welcome to AI Business Consultant.", "success");
        navigateTo('dashboard');
    };
}

function handleLogout() {
    AppState.currentUser = null;
    localStorage.removeItem('biz_current_user');
    AppState.profile = null;
    AppState.chatMessages = [];
    showAlert("You have been successfully logged out.", "info");
    navigateTo('login');
}

// ------------------------------------------------------------------------------
// 2. DASHBOARD MODULE
// ------------------------------------------------------------------------------

function renderDashboardView(container) {
    const user = AppState.currentUser;
    const profile = AppState.profile || getStoredProfile(user.id);
    const chat = AppState.chatMessages || getStoredChat(user.id);

    container.innerHTML = `
        <div class="card" style="background: linear-gradient(135deg, #1E3A8A 0%, #1E40AF 100%); color: white;">
            <div style="display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 1rem;">
                <div>
                    <h1 style="font-size: 1.8rem; font-weight: 800;">Welcome back, ${escapeHtml(user.name)}!</h1>
                    <p style="opacity: 0.9; margin-top: 0.3rem;">
                        Enterprise executive strategy & multimodal business audit powered by Gemini 2.5 Flash.
                    </p>
                </div>
                <div>
                    ${profile && profile.businessName ? `
                        <span style="background: rgba(255,255,255,0.2); padding: 0.4rem 0.8rem; border-radius: 20px; font-size: 0.88rem;">
                            🏢 ${escapeHtml(profile.businessName)} (${escapeHtml(profile.industry || 'General')})
                        </span>
                    ` : ''}
                </div>
            </div>
        </div>

        ${!getActiveApiKey() ? `
            <div class="alert alert-warning">
                <span>⚠️ <strong>Gemini API Key Required:</strong> Click the button below to paste your free Google Gemini API key to activate AI responses.</span>
                <button class="btn btn-secondary btn-sm" onclick="openApiKeyModal()">Enter API Key</button>
            </div>
        ` : ''}

        <h2 style="font-size: 1.3rem; margin-top: 1.5rem; margin-bottom: 0.5rem; color: var(--primary);">
            Executive Modules
        </h2>

        <div class="dashboard-grid">
            <!-- Module 1: Ask AI Consultant -->
            <div class="module-card" onclick="navigateTo('chat')">
                <div>
                    <div class="module-icon">💬</div>
                    <div class="module-title">Ask AI Consultant</div>
                    <div class="module-desc">
                        Consult on pricing optimization, marketing funnels, sales bottlenecks, and competitive differentiation.
                    </div>
                </div>
                <div style="display: flex; justify-content: space-between; align-items: center; font-size: 0.85rem; color: var(--secondary); font-weight: 600;">
                    <span>${chat.length} messages</span>
                    <span>Open Consultation &rarr;</span>
                </div>
            </div>

            <!-- Module 2: Image Analysis -->
            <div class="module-card" onclick="navigateTo('image-analysis')">
                <div>
                    <div class="module-icon">📸</div>
                    <div class="module-title">Image Analysis</div>
                    <div class="module-desc">
                        Upload shopfronts, product packaging, invoices, or revenue charts for multimodal computer vision audit.
                    </div>
                </div>
                <div style="display: flex; justify-content: space-between; align-items: center; font-size: 0.85rem; color: var(--secondary); font-weight: 600;">
                    <span>Multimodal AI Vision</span>
                    <span>Audit Asset &rarr;</span>
                </div>
            </div>

            <!-- Module 3: Business Profile -->
            <div class="module-card" onclick="navigateTo('profile')">
                <div>
                    <div class="module-icon">📊</div>
                    <div class="module-title">Business Profile</div>
                    <div class="module-desc">
                        Manage your company industry, budget, goals, and target customers to personalize all Gemini recommendations.
                    </div>
                </div>
                <div style="display: flex; justify-content: space-between; align-items: center; font-size: 0.85rem; color: var(--secondary); font-weight: 600;">
                    <span>${profile && profile.businessName ? 'Configured' : 'Incomplete'}</span>
                    <span>Manage Profile &rarr;</span>
                </div>
            </div>

            <!-- Module 4: Sign Out -->
            <div class="module-card" style="border-color: #FECACA;" onclick="handleLogout()">
                <div>
                    <div class="module-icon">🚪</div>
                    <div class="module-title" style="color: var(--danger);">Logout</div>
                    <div class="module-desc">
                        Safely end your current business consulting session and clear session credentials.
                    </div>
                </div>
                <div style="text-align: right; font-size: 0.85rem; color: var(--danger); font-weight: 600;">
                    <span>Sign Out &rarr;</span>
                </div>
            </div>
        </div>

        <!-- Business Context Overview -->
        ${profile ? `
            <div class="card" style="margin-top: 1.8rem;">
                <div class="card-header">
                    <h3 class="card-title" style="font-size: 1.15rem;">🏢 Active Business Intelligence Context</h3>
                    <p class="card-subtitle">AI recommendations are tailored using these parameters</p>
                </div>
                <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem;">
                    <div>
                        <strong style="color: var(--text-muted); font-size: 0.82rem; text-transform: uppercase;">Company Name</strong>
                        <p style="font-weight: 600;">${escapeHtml(profile.businessName || 'Not set')}</p>
                    </div>
                    <div>
                        <strong style="color: var(--text-muted); font-size: 0.82rem; text-transform: uppercase;">Industry</strong>
                        <p style="font-weight: 600;">${escapeHtml(profile.industry || 'Not set')}</p>
                    </div>
                    <div>
                        <strong style="color: var(--text-muted); font-size: 0.82rem; text-transform: uppercase;">Budget</strong>
                        <p style="font-weight: 600;">${escapeHtml(profile.budget || 'Not set')}</p>
                    </div>
                    <div>
                        <strong style="color: var(--text-muted); font-size: 0.82rem; text-transform: uppercase;">Strategic Goals</strong>
                        <p style="font-weight: 600;">${escapeHtml(profile.goals || 'Not set')}</p>
                    </div>
                </div>
            </div>
        ` : ''}
    `;
}

// ------------------------------------------------------------------------------
// 3. AI CHAT MODULE (Ask AI Consultant)
// ------------------------------------------------------------------------------

function renderChatView(container) {
    const user = AppState.currentUser;
    const profile = AppState.profile || getStoredProfile(user.id);
    const messages = AppState.chatMessages || getStoredChat(user.id);

    container.innerHTML = `
        <div class="card" style="margin-bottom: 1rem; padding: 1.2rem;">
            <div style="display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 0.8rem;">
                <div>
                    <h1 class="card-title" style="font-size: 1.3rem;">💬 Executive AI Business Consultant</h1>
                    <p class="card-subtitle">
                        ${profile && profile.businessName ? `Context: <strong>${escapeHtml(profile.businessName)}</strong> (${escapeHtml(profile.industry || 'General')})` : 'General Business Advisory'}
                    </p>
                </div>
                <div style="display: flex; gap: 0.5rem;">
                    ${messages.length > 0 ? `
                        <button class="btn btn-secondary btn-sm" id="clearChatBtn">
                            🗑️ Clear History
                        </button>
                    ` : ''}
                    <button class="btn btn-secondary btn-sm" onclick="navigateTo('dashboard')">
                        &larr; Dashboard
                    </button>
                </div>
            </div>
        </div>

        ${!getActiveApiKey() ? `
            <div class="alert alert-warning">
                <span>⚠️ <strong>Gemini API Key Required:</strong> Click below to configure your key and start asking questions.</span>
                <button class="btn btn-secondary btn-sm" onclick="openApiKeyModal()">Set Key</button>
            </div>
        ` : ''}

        <div class="chat-container">
            <div class="chat-history" id="chatHistoryBox">
                ${messages.length === 0 ? `
                    <div style="text-align: center; margin: auto; padding: 2rem; color: var(--text-muted); max-width: 500px;">
                        <div style="font-size: 2.5rem; margin-bottom: 0.5rem;">💡</div>
                        <h3 style="color: var(--text-main); margin-bottom: 0.4rem;">How can I assist your business today?</h3>
                        <p style="font-size: 0.9rem; margin-bottom: 1.5rem;">
                            Ask any strategic question on revenue, customer growth, marketing tactics, or operational scaling.
                        </p>
                        <div style="display: flex; flex-direction: column; gap: 0.5rem; text-align: left;">
                            <button class="btn btn-secondary quick-prompt" onclick="useQuickPrompt('How to improve my sales for the upcoming quarter?')">
                                📈 "How to improve my sales for the upcoming quarter?"
                            </button>
                            <button class="btn btn-secondary quick-prompt" onclick="useQuickPrompt('Suggest marketing strategy for a small bakery')">
                                🥐 "Suggest marketing strategy for a small bakery"
                            </button>
                            <button class="btn btn-secondary quick-prompt" onclick="useQuickPrompt('How can I optimize pricing to increase profit margins?')">
                                🏷️ "How can I optimize pricing to increase profit margins?"
                            </button>
                        </div>
                    </div>
                ` : messages.map(m => `
                    <div class="chat-bubble ${m.sender === 'user' ? 'user' : 'ai'}">
                        <div class="chat-bubble-header">
                            <span>${m.sender === 'user' ? '👤 ' + escapeHtml(user.name) : '🤖 AI Business Consultant'}</span>
                            <span style="font-weight: normal; opacity: 0.7;">${m.time || ''}</span>
                        </div>
                        <div>${escapeHtml(m.content)}</div>
                    </div>
                `).join('')}
            </div>

            <form id="chatInputForm" class="chat-input-bar">
                <input type="text" id="chatInputText" class="form-control" placeholder="Ask your business question (e.g. 'How to improve my sales?')..." autocomplete="off" required>
                <button type="submit" class="btn btn-primary" id="chatSubmitBtn">
                    Send Inquiry &rarr;
                </button>
            </form>
        </div>
    `;

    // Auto-scroll chat to bottom
    const box = document.getElementById('chatHistoryBox');
    if (box) box.scrollTop = box.scrollHeight;

    // Clear history button
    const clearBtn = document.getElementById('clearChatBtn');
    if (clearBtn) {
        clearBtn.onclick = () => {
            if (confirm("Clear all consultation history?")) {
                AppState.chatMessages = [];
                saveStoredChat(user.id, []);
                renderChatView(container);
            }
        };
    }

    // Chat submit
    const form = document.getElementById('chatInputForm');
    const input = document.getElementById('chatInputText');
    const submitBtn = document.getElementById('chatSubmitBtn');

    form.onsubmit = async (e) => {
        e.preventDefault();
        const text = input.value.trim();
        if (!text) return;

        input.value = '';
        submitBtn.disabled = true;
        submitBtn.innerText = "Consulting Gemini...";

        const timeStr = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
        const userMsg = { sender: 'user', content: text, time: timeStr };
        AppState.chatMessages.push(userMsg);
        saveStoredChat(user.id, AppState.chatMessages);

        // Re-render chat messages quickly
        renderChatView(container);

        try {
            const aiReply = await callGeminiText(text, profile);
            const aiMsg = { sender: 'ai', content: aiReply, time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) };
            AppState.chatMessages.push(aiMsg);
            saveStoredChat(user.id, AppState.chatMessages);
        } catch (err) {
            const errMsg = { sender: 'ai', content: `⚠️ Error: ${err.message}\n\nPlease check your Gemini API key in the top right.`, time: timeStr };
            AppState.chatMessages.push(errMsg);
            saveStoredChat(user.id, AppState.chatMessages);
            showAlert(err.message, "danger");
        }

        renderChatView(container);
    };
}

function useQuickPrompt(text) {
    const input = document.getElementById('chatInputText');
    if (input) {
        input.value = text;
        const form = document.getElementById('chatInputForm');
        if (form) form.requestSubmit();
    }
}

// ------------------------------------------------------------------------------
// 4. IMAGE ANALYSIS MODULE
// ------------------------------------------------------------------------------

function renderImageView(container) {
    const user = AppState.currentUser;
    const profile = AppState.profile || getStoredProfile(user.id);

    container.innerHTML = `
        <div class="card">
            <div style="display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 0.8rem;">
                <div>
                    <h1 class="card-title">📸 Multimodal Image Analysis & Audit</h1>
                    <p class="card-subtitle">
                        Upload storefronts, retail displays, product photos, invoices, or revenue charts for instant AI audit.
                    </p>
                </div>
                <button class="btn btn-secondary btn-sm" onclick="navigateTo('dashboard')">
                    &larr; Dashboard
                </button>
            </div>

            ${!getActiveApiKey() ? `
                <div class="alert alert-warning" style="margin-top: 1rem;">
                    <span>⚠️ <strong>Gemini API Key Required:</strong> Click below to configure your Gemini API key for image analysis.</span>
                    <button class="btn btn-secondary btn-sm" onclick="openApiKeyModal()">Set Key</button>
                </div>
            ` : ''}

            <form id="imageUploadForm" style="margin-top: 1.5rem;">
                <div class="form-group">
                    <label for="imageFileInput" class="form-label">Select Business Image (JPG, JPEG, PNG • Max 5MB)</label>
                    <input type="file" id="imageFileInput" class="form-control" accept=".jpg,.jpeg,.png,image/jpeg,image/png" required>
                </div>

                <div class="form-group">
                    <label for="imageCustomPrompt" class="form-label">Specific Question or Focus (Optional)</label>
                    <input type="text" id="imageCustomPrompt" class="form-control" placeholder="e.g. 'Critique store shelf layout', 'Identify pricing or packaging flaws'">
                </div>

                <!-- Live Preview Container -->
                <div id="imagePreviewContainer" class="preview-container" style="display: ${AppState.selectedImageBase64 ? 'block' : 'none'};">
                    <img id="imagePreviewElement" class="image-preview" src="${AppState.selectedImageBase64 ? `data:${AppState.selectedImageMime};base64,${AppState.selectedImageBase64}` : ''}" alt="Image Preview">
                </div>

                <button type="submit" class="btn btn-primary" id="analyzeImageBtn" style="margin-top: 0.5rem;" ${!AppState.selectedImageBase64 ? 'disabled' : ''}>
                    🔍 Run Multimodal AI Audit
                </button>
            </form>
        </div>

        <div id="imageResultsContainer"></div>
    `;

    const fileInput = document.getElementById('imageFileInput');
    const previewContainer = document.getElementById('imagePreviewContainer');
    const previewElement = document.getElementById('imagePreviewElement');
    const analyzeBtn = document.getElementById('analyzeImageBtn');
    const uploadForm = document.getElementById('imageUploadForm');

    fileInput.onchange = (e) => {
        const file = e.target.files[0];
        if (!file) return;

        if (!file.type.match(/^image\/(jpeg|jpg|png)$/i)) {
            showAlert("Invalid file format. Please upload a JPG or PNG image.", "danger");
            fileInput.value = '';
            return;
        }

        if (file.size > 5 * 1024 * 1024) {
            showAlert("File is too large (maximum size is 5MB). Please upload a smaller image.", "danger");
            fileInput.value = '';
            return;
        }

        const reader = new FileReader();
        reader.onload = (event) => {
            const dataUrl = event.target.result;
            const parts = dataUrl.split(',');
            AppState.selectedImageMime = file.type;
            AppState.selectedImageBase64 = parts[1];

            previewElement.src = dataUrl;
            previewContainer.style.display = 'block';
            analyzeBtn.disabled = false;
        };
        reader.readAsDataURL(file);
    };

    uploadForm.onsubmit = async (e) => {
        e.preventDefault();
        if (!AppState.selectedImageBase64) {
            showAlert("Please select an image to analyze first.", "warning");
            return;
        }

        const customPrompt = document.getElementById('imageCustomPrompt').value.trim();
        const resultsContainer = document.getElementById('imageResultsContainer');

        analyzeBtn.disabled = true;
        analyzeBtn.innerHTML = "Analyzing with Gemini Vision...";
        resultsContainer.innerHTML = `
            <div class="card" style="text-align:center; padding: 2rem;">
                <p>🔍 <strong>AI Consultant is auditing your image with Gemini 2.5 Flash...</strong></p>
            </div>
        `;

        try {
            const analysis = await callGeminiVision(AppState.selectedImageBase64, AppState.selectedImageMime, customPrompt, profile);
            resultsContainer.innerHTML = `
                <div class="card">
                    <div class="card-header">
                        <h2 class="card-title" style="font-size: 1.25rem;">🔍 AI Strategic Audit & Recommendations</h2>
                        <p class="card-subtitle">${customPrompt ? `Focus: "${escapeHtml(customPrompt)}"` : 'Comprehensive Executive Audit'}</p>
                    </div>
                    <div class="ai-output-box">${escapeHtml(analysis)}</div>
                </div>
            `;
            showAlert("Image audit completed successfully!", "success");
        } catch (err) {
            resultsContainer.innerHTML = '';
            showAlert(`Analysis failed: ${err.message}`, "danger");
        } finally {
            analyzeBtn.disabled = false;
            analyzeBtn.innerHTML = "🔍 Run Multimodal AI Audit";
        }
    };
}

// ------------------------------------------------------------------------------
// 5. BUSINESS PROFILE MODULE
// ------------------------------------------------------------------------------

function renderProfileView(container) {
    const user = AppState.currentUser;
    const profile = AppState.profile || getStoredProfile(user.id);

    container.innerHTML = `
        <div class="card">
            <div style="display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 0.8rem;">
                <div>
                    <h1 class="card-title">📊 Business Profile Management</h1>
                    <p class="card-subtitle">
                        Configure your company parameters. All Gemini advice will be contextualized with this profile.
                    </p>
                </div>
                <button class="btn btn-secondary btn-sm" onclick="navigateTo('dashboard')">
                    &larr; Dashboard
                </button>
            </div>

            <form id="profileForm" style="margin-top: 1.5rem;">
                <div class="form-group">
                    <label for="profBizName" class="form-label">Business / Venture Name *</label>
                    <input type="text" id="profBizName" class="form-control" placeholder="e.g. Apex Artisanal Bakery" value="${escapeHtml(profile.businessName || '')}" required>
                </div>

                <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 1rem;">
                    <div class="form-group">
                        <label for="profIndustry" class="form-label">Industry / Sector</label>
                        <input type="text" id="profIndustry" class="form-control" placeholder="e.g. Food & Beverage / Retail / E-commerce" value="${escapeHtml(profile.industry || '')}">
                    </div>

                    <div class="form-group">
                        <label for="profBudget" class="form-label">Monthly / Operating Budget</label>
                        <input type="text" id="profBudget" class="form-control" placeholder="e.g. $15,000 / month" value="${escapeHtml(profile.budget || '')}">
                    </div>
                </div>

                <div class="form-group">
                    <label for="profGoals" class="form-label">Strategic Goals</label>
                    <textarea id="profGoals" class="form-control" rows="3" placeholder="e.g. Double repeat customer visits within 6 months, scale organic revenue">${escapeHtml(profile.goals || '')}</textarea>
                </div>

                <div class="form-group">
                    <label for="profCustomers" class="form-label">Target Customers & Demographics</label>
                    <textarea id="profCustomers" class="form-control" rows="3" placeholder="e.g. Health-conscious urban professionals aged 25-45 looking for organic artisan baked goods">${escapeHtml(profile.targetCustomers || '')}</textarea>
                </div>

                <button type="submit" class="btn btn-primary" style="margin-top: 0.5rem;">
                    💾 Save Business Profile
                </button>
            </form>
        </div>

        <!-- Saved Overview Display -->
        <div class="card" style="margin-top: 1.5rem; background: var(--bg-card);">
            <div class="card-header">
                <h2 class="card-title" style="font-size: 1.15rem;">🏢 Active Saved Profile</h2>
                <p class="card-subtitle">Active parameters used by AI Business Consultant</p>
            </div>
            <div style="display: flex; flex-direction: column; gap: 0.8rem; font-size: 0.95rem;">
                <div><strong style="color: var(--primary);">Business Name:</strong> <span id="viewBizName">${escapeHtml(profile.businessName || 'Not specified')}</span></div>
                <div><strong style="color: var(--primary);">Industry:</strong> <span id="viewIndustry">${escapeHtml(profile.industry || 'Not specified')}</span></div>
                <div><strong style="color: var(--primary);">Budget:</strong> <span id="viewBudget">${escapeHtml(profile.budget || 'Not specified')}</span></div>
                <div><strong style="color: var(--primary);">Goals:</strong> <span id="viewGoals">${escapeHtml(profile.goals || 'Not specified')}</span></div>
                <div><strong style="color: var(--primary);">Target Audience:</strong> <span id="viewCustomers">${escapeHtml(profile.targetCustomers || 'Not specified')}</span></div>
            </div>
        </div>
    `;

    document.getElementById('profileForm').onsubmit = (e) => {
        e.preventDefault();
        const bizName = document.getElementById('profBizName').value.trim();
        if (!bizName) {
            showAlert("Business name is required.", "danger");
            return;
        }

        const updatedProfile = {
            businessName: bizName,
            industry: document.getElementById('profIndustry').value.trim(),
            budget: document.getElementById('profBudget').value.trim(),
            goals: document.getElementById('profGoals').value.trim(),
            targetCustomers: document.getElementById('profCustomers').value.trim(),
            updatedAt: new Date().toISOString()
        };

        AppState.profile = updatedProfile;
        saveStoredProfile(user.id, updatedProfile);

        showAlert("Business profile saved successfully! AI will now use these parameters.", "success");
        renderProfileView(container);
    };
}

// ------------------------------------------------------------------------------
// API KEY CONFIGURATION MODAL
// ------------------------------------------------------------------------------

function openApiKeyModal() {
    let modal = document.getElementById('apiKeyModal');
    if (!modal) {
        modal = document.createElement('div');
        modal.id = 'apiKeyModal';
        modal.className = 'modal-overlay';
        document.body.appendChild(modal);
    }

    modal.innerHTML = `
        <div class="modal-content">
            <h2 style="font-size: 1.3rem; margin-bottom: 0.5rem; color: var(--primary);">⚙️ Configure Google Gemini API Key</h2>
            <p style="font-size: 0.9rem; color: var(--text-muted); margin-bottom: 1.2rem;">
                Enter your Google Gemini API key to enable live AI Business Consultant Q&A and Multimodal Image Analysis on Vercel.
            </p>
            <div class="form-group">
                <label class="form-label">Gemini API Key (AIzaSy...)</label>
                <input type="text" id="modalKeyInput" class="form-control" placeholder="Paste your API key here" value="${escapeHtml(AppState.apiKey)}">
            </div>
            <p style="font-size: 0.82rem; color: var(--text-muted); margin-bottom: 1.5rem;">
                Get a free API key at <a href="https://aistudio.google.com/" target="_blank" style="color:var(--secondary);font-weight:600;">aistudio.google.com</a>.
            </p>
            <div style="display: flex; justify-content: flex-end; gap: 0.8rem;">
                <button class="btn btn-secondary" onclick="closeApiKeyModal()">Cancel</button>
                <button class="btn btn-primary" onclick="saveApiKeyModal()">Save Key</button>
            </div>
        </div>
    `;
    modal.style.display = 'flex';
}

function closeApiKeyModal() {
    const modal = document.getElementById('apiKeyModal');
    if (modal) modal.style.display = 'none';
}

function saveApiKeyModal() {
    const input = document.getElementById('modalKeyInput');
    if (input) {
        const key = input.value.trim();
        AppState.apiKey = key;
        localStorage.setItem('gemini_api_key', key);
        showAlert("Gemini API Key updated!", "success");
        closeApiKeyModal();
        renderNavbar();
    }
}

// Helper to escape HTML characters
function escapeHtml(text) {
    if (!text) return '';
    return String(text)
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#039;');
}

// ==============================================================================
// INITIALIZATION
// ==============================================================================

window.addEventListener('DOMContentLoaded', () => {
    // Restore user session if stored
    try {
        const savedUser = localStorage.getItem('biz_current_user');
        if (savedUser) {
            AppState.currentUser = JSON.parse(savedUser);
            AppState.profile = getStoredProfile(AppState.currentUser.id);
            AppState.chatMessages = getStoredChat(AppState.currentUser.id);
        }
    } catch (e) {
        AppState.currentUser = null;
    }

    // Handle hash change & popstate
    window.addEventListener('hashchange', () => {
        renderRoute(getNormalizedRoute());
    });

    window.addEventListener('popstate', () => {
        renderRoute(getNormalizedRoute());
    });

    // Initial render
    renderRoute(getNormalizedRoute());
});
